### ISSUE TITLE
IsotopX PhoeniX Data parsing

### ISSUE THREAD

**Issue by ryanickert** [bowring/Tripoli#1]
Hi Folks, attached is a TIMSDP file from the latest iteration of the Phoenix software.  It appears to be basically a csv file and straightforward to parse.

[Sr Dyn 20-11-8-106.zip](https://github.com/bowring/Tripoli/files/5631902/Sr.Dyn.20-11-8-106.zip)

**Comment by ryanickert** [comment]
Sorry, that's not very specific.  It would be great if Tripoli could recognize and import the TIMSDP files so they can be used natively.

**Comment by bowring** [comment]
basically you just want the cycles data with all the labels except 'cycle' and 'time'?:
```
#CYCLES
Cycle,Time,Sr84 Kr84 S1,Rb85 S1,Rb85 S2,Rb85 S3,Sr86 S1,Sr86 S2,Sr86 S3,Sr87 S1,Sr87 S2,Sr87 S3,88 S1,88 S2,88 S3,86/88 Raw S2,87-85 S1,87-85 S2,87-85 S3,87/86 S1 S2,87/86 S2 S3,87/86 Mean,Conversion Factor,87/86 Exp,84/86 Raw,86/88 S3,beta,86/88 S1,87/86 S1 Exp,87/86 S2 Exp,87/86 S3 Exp
```
Giving, for example:
![tripoliExamp](https://user-images.githubusercontent.com/1092963/101167753-678f1280-3608-11eb-822a-81862b024460.png)

**Comment by ryanickert** [comment]
Yes, and if it's not a hassle, including "time" would be useful too.
