### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by ryanickert** [bowring/Tripoli#2]
It would be useful to be able to plot and calculate negative numbers in Tripoli, if that doesn't break other functionality.  I often output delta-values (fractional differences from a reference value) that can be negative.

**Comment by bowring** [comment]
A design flaw from 20 years ago makes it complicated- at the time I was assured that there would never be negative values, so the simplistic way of flagging that a value has been rejected is to make it negative, which is what Tripoli does.  The new MC-Tripoli that Noah, Scott, and I are trying to get funded won't be bound by such constraints.  The fix would be time-consuming.  A work-around would be a special mode where some alpha is added to every value to shift all into positive territory.

**Comment by ryanickert** [comment]
Hi Jim - thanks for the feedback.  That's good to know and it's clearly not worth the hassle.
