### ISSUE TITLE
unable to open phoenix dsdp files in Tripoli

### ISSUE THREAD

**Issue by ryanickert** [bowring/Tripoli#4]
[Ickert_Phoenix_Issue.zip](https://github.com/bowring/Tripoli/files/6305215/Ickert_Phoenix_Issue.zip)

Using Tripoli 4.10.0.0 on a 64 bit Windows PC running Windows 10 education, when I try to open dsdp files generated by Isolinx 1.2.31 on the Phoenix TIMS, the files are not opened.  No error messages are generated.  I have attached four dsdp files as examples.  Included are .csv versions that I generated autmatically (using a script) from the dsdp files that *do* work in tripoli 4.10.0.0.  The original Sr dataset that I uploaded for a previous issue will open in Tripoli 4.10.0.0.

**Comment by bowring** [comment]
The problem is you changed the date format for analysis start and end ... can be adapted to, but WTF?
new files:
AnalysisStart,2021-04-06 3:51:16 PM
AnalysisEnd,2021-04-06 5:27:43 PM

used to be:
AnalysisStart,09/11/2020 00:48:33
AnalysisEnd,09/11/2020 00:48:33

standby for update (in the meantime change your dates and all should be fine)

**Comment by ryanickert** [comment]
I've never looked at this piece of metadata, so I don't know whether it's inherited from the time-date format set by windows or by Isolinx - if it's Isolinx there's not much I can do about it.  There were some date-time issues that needed to be ironed out during install, at least one of which required a software patch, I think, and that could have been where the change was introduced.

If it is tied to windows settings, though, won't this break every time someone changes the date-time format on their computer?

**Comment by bowring** [comment]
It is purely a text parsing problem related to how the software writes dates, which is not driven by windows - the new format of yyyy-mm-dd is much more universal, and the old format can still be parsed correctly.
